version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
      MONGO_INITDB_DATABASE: issuetracker
    volumes:
      - /mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d/
