services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:secret123@mongo:27017/issuetracker?authSource=admin
      - ALLOWED_ORIGINS=*
    volumes:
      - ./uploads:/app/uploads

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
      MONGO_INITDB_DATABASE: issuetracker
    volumes:
      - /mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d/
